In [39]:
import numpy as np

In [40]:
np.__version__

'1.20.3'

In [41]:
import pandas as pd
url_data = (r'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
data = pd.read_csv(url_data)
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [42]:
len(data)

11914

In [64]:
data.groupby('Make').size().sort_values(ascending=False).head(3)

Make
Chevrolet     1123
Ford           881
Volkswagen     809
dtype: int64

In [44]:
data[data.Make=='Audi']['Model'].nunique()

34

In [45]:
count_missing=data.isna().sum().sort_values(ascending=False).to_frame('sum_missing').reset_index()
count_missing
len(count_missing[count_missing.sum_missing!=0])

5

In [46]:
data['Engine Cylinders'].median()

6.0

In [47]:
data['Engine Cylinders'].mode()

0    4.0
dtype: float64

In [48]:
data['Engine Cylinders']=data['Engine Cylinders'].fillna(data['Engine Cylinders'].mode())

In [49]:
data['Engine Cylinders'].median()

6.0

In [50]:
data[data.Make=='Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [51]:
X=data[data.Make=='Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates().to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [56]:
XTX = np.mat(X.T) * np.mat(X)
XTX

matrix([[7.31684e+05, 1.34100e+04],
        [1.34100e+04, 2.52000e+02]])

In [57]:
XTX_inv = np.linalg.inv(XTX)

In [58]:
y=np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [61]:
w = np.matmul(np.matmul(XTX_inv, X.T), y)
w

matrix([[  4.59494481, -63.56432501]])